
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rerfghtchrakecxcyima.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlcmZnaHRjaHJha2VjeGN5aW1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5NzYyMzcsImV4cCI6MjA1NzU1MjIzN30.VRlKuouxLv7ZfAYZIKS7viO_MKZE6fOsh938oLozXh4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
