// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uazcmusqroaxpgndzvqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhemNtdXNxcm9heHBnbmR6dnFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4MDQyMzEsImV4cCI6MjA1NzM4MDIzMX0.vt44-64REGzxEYaIYBMdxXptzNeUUUYPK63lREjtMfQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);